### ISSUE TITLE
Доработки по TODO тегам

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/sj_studio#28]
Все TODO теги взяты из кода. Необходимо зафиксить зафиксить
- [ ] необходимо указать в стилях нужный фон секции
- [ ] this element need review
- [ ] решить проблему с дублирующимися тегами
- [ ] после подтверждения локации, данный код будет обновлен
- [x] необходимо разобраться как правильно сделать кликабельную ссылку на почту
